### ISSUE TITLE
Error: Cannot gist empty files

### ISSUE THREAD

**Issue by Strykar** [Ventto/bacpac#10]
Pug was working fine for months and today, when I uninstalled a foreign package, I got:
```
:: Processing gists update...
Error: Cannot gist empty files
:: Failed to update.
error: command failed to execute correctly
```
Possibly related to https://github.com/Ventto/pug/issues/2

EDIT:
It now fails with standard package upgrades too:
```
:: Processing gists update...
Error: Cannot gist empty files
:: Failed to update.
error: command failed to execute correctly
```

**Comment by Ventto** [comment]
Hey @Strykar,
Thanks for the feedback, I will take a look at it soon.
Accordingly, I've reopened the issue you have mentioned.

**Comment by Ventto** [comment]
Could you precise what do you mean by "foreign package" ?
Is the issue reproducible with any "foreign package" ? If not, which one was it ?

**Comment by Strykar** [comment]
@Ventto I actually removed the foreign package to weed out that being an issue, but the problem remains.
The issue is intermittently buggy now, sometimes, it creates 2 gists, sometimes no errors and typically it fails as above.
If there's any way I could assist in troubleshooting this, I would be happy to.

**Comment by Strykar** [comment]
I cannot reproduce this anymore, closing.
