### ISSUE TITLE
Support for multiple installs

### ISSUE THREAD

**Issue by plastboks** [Ventto/bacpac#4]
Hi.
I might have overlooked something central, but what is the multiple installs support like? Would the gists files be overwritten if the set of installed packages is not the same?

I have Arch installed on multiple machines, and does not necessary want the same set of installed packages distributed on all of them.

Would something as simple as:
```bash
PACMANFILE="$HOSTNAME-pacman-list.pkg"
AURFILE="$HOSTNAME-aur-list.pkg"
```
solve this?

**Comment by Ventto** [comment]
@plastboks, thanks for the feedback.

I could ask for custom filenames or prefixes at setup, `pacman-list.pkg` and `aur-list.pkg` if not.

**Comment by plastboks** [comment]
Yeah that would work out fine 👍

**Comment by cmonty14** [comment]
Hi,
I like your tool.
But I miss the feature requested here.

Can you update the status on this feature request?

THX
