### ISSUE TITLE
Merging Upstream

### ISSUE THREAD

**Issue by DerekTBrown** [Ventto/bacpac#5]
Just found out about **pug**.  Super cool- love the color highlighting. It seems the project is downstream of [pacmanity](https://github.com/Ventto/pug/commit/2c7f141afa8944b847fa1b7cd1b09c4b11ce3b68), a project I maintain.  I would love to add these features upstream.  Would you be interested in merging the packages / becoming a maintainer?

**Comment by Ventto** [comment]
With pleasure ! Some frustrations to implement yet. Keep in touch.

**Comment by Ventto** [comment]
Hi @DerekTBrown,
Now I've made my comeback and it is time to merge *pug* with *pacmanity*.
Hope I will have enough time.
My apologies for the huge delay.
